/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourRouteImport } from './routes/tour'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as FrRouteImport } from './routes/fr'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TourSlugRouteImport } from './routes/tour_.$slug'
import { Route as FrTourRouteImport } from './routes/fr_.tour'
import { Route as FrDestinationsRouteImport } from './routes/fr_.destinations'
import { Route as FrAttractionsRouteImport } from './routes/fr_.attractions'
import { Route as FrSlugRouteImport } from './routes/fr_.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations_.$slug'
import { Route as DestinationBeratRouteImport } from './routes/destination.berat'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminTaxonomiesRouteImport } from './routes/admin.taxonomies'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminToursIndexRouteImport } from './routes/admin.tours.index'
import { Route as AdminDestinationsIndexRouteImport } from './routes/admin.destinations.index'
import { Route as AdminAttractionsIndexRouteImport } from './routes/admin.attractions.index'
import { Route as FrTourSlugRouteImport } from './routes/fr_.tour_.$slug'
import { Route as FrDestinationsSlugRouteImport } from './routes/fr_.destinations_.$slug'
import { Route as AttractionsDestinationSlugSlugRouteImport } from './routes/attractions_.$destinationSlug.$slug'
import { Route as AdminToursNewRouteImport } from './routes/admin.tours.new'
import { Route as AdminToursTourIdRouteImport } from './routes/admin.tours.$tourId'
import { Route as AdminDestinationsNewRouteImport } from './routes/admin.destinations.new'
import { Route as AdminDestinationsPlaceIdRouteImport } from './routes/admin.destinations.$placeId'
import { Route as AdminAttractionsNewRouteImport } from './routes/admin.attractions.new'
import { Route as AdminAttractionsPlaceIdRouteImport } from './routes/admin.attractions.$placeId'
import { Route as FrAttractionsDestinationSlugSlugRouteImport } from './routes/fr_.attractions_.$destinationSlug.$slug'
import { Route as AdminToursTourIdPreviewRouteImport } from './routes/admin_.tours.$tourId.preview'

const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TourSlugRoute = TourSlugRouteImport.update({
  id: '/tour_/$slug',
  path: '/tour/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrTourRoute = FrTourRouteImport.update({
  id: '/fr_/tour',
  path: '/fr/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const FrDestinationsRoute = FrDestinationsRouteImport.update({
  id: '/fr_/destinations',
  path: '/fr/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FrAttractionsRoute = FrAttractionsRouteImport.update({
  id: '/fr_/attractions',
  path: '/fr/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const FrSlugRoute = FrSlugRouteImport.update({
  id: '/fr_/$slug',
  path: '/fr/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations_/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationBeratRoute = DestinationBeratRouteImport.update({
  id: '/destination/berat',
  path: '/destination/berat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTaxonomiesRoute = AdminTaxonomiesRouteImport.update({
  id: '/taxonomies',
  path: '/taxonomies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursIndexRoute = AdminToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsIndexRoute = AdminDestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttractionsIndexRoute = AdminAttractionsIndexRouteImport.update({
  id: '/attractions/',
  path: '/attractions/',
  getParentRoute: () => AdminRoute,
} as any)
const FrTourSlugRoute = FrTourSlugRouteImport.update({
  id: '/fr_/tour_/$slug',
  path: '/fr/tour/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrDestinationsSlugRoute = FrDestinationsSlugRouteImport.update({
  id: '/fr_/destinations_/$slug',
  path: '/fr/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsDestinationSlugSlugRoute =
  AttractionsDestinationSlugSlugRouteImport.update({
    id: '/attractions_/$destinationSlug/$slug',
    path: '/attractions/$destinationSlug/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminToursNewRoute = AdminToursNewRouteImport.update({
  id: '/tours/new',
  path: '/tours/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursTourIdRoute = AdminToursTourIdRouteImport.update({
  id: '/tours/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsNewRoute = AdminDestinationsNewRouteImport.update({
  id: '/destinations/new',
  path: '/destinations/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsPlaceIdRoute =
  AdminDestinationsPlaceIdRouteImport.update({
    id: '/destinations/$placeId',
    path: '/destinations/$placeId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAttractionsNewRoute = AdminAttractionsNewRouteImport.update({
  id: '/attractions/new',
  path: '/attractions/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttractionsPlaceIdRoute = AdminAttractionsPlaceIdRouteImport.update({
  id: '/attractions/$placeId',
  path: '/attractions/$placeId',
  getParentRoute: () => AdminRoute,
} as any)
const FrAttractionsDestinationSlugSlugRoute =
  FrAttractionsDestinationSlugSlugRouteImport.update({
    id: '/fr_/attractions_/$destinationSlug/$slug',
    path: '/fr/attractions/$destinationSlug/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminToursTourIdPreviewRoute = AdminToursTourIdPreviewRouteImport.update({
  id: '/admin_/tours/$tourId/preview',
  path: '/admin/tours/$tourId/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/attractions': typeof AttractionsRoute
  '/destinations': typeof DestinationsRoute
  '/fr': typeof FrRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tour': typeof TourRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/taxonomies': typeof AdminTaxonomiesRoute
  '/admin/login': typeof AdminLoginRoute
  '/destination/berat': typeof DestinationBeratRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/fr/$slug': typeof FrSlugRoute
  '/fr/attractions': typeof FrAttractionsRoute
  '/fr/destinations': typeof FrDestinationsRoute
  '/fr/tour': typeof FrTourRoute
  '/tour/$slug': typeof TourSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/attractions/$placeId': typeof AdminAttractionsPlaceIdRoute
  '/admin/attractions/new': typeof AdminAttractionsNewRoute
  '/admin/destinations/$placeId': typeof AdminDestinationsPlaceIdRoute
  '/admin/destinations/new': typeof AdminDestinationsNewRoute
  '/admin/tours/$tourId': typeof AdminToursTourIdRoute
  '/admin/tours/new': typeof AdminToursNewRoute
  '/attractions/$destinationSlug/$slug': typeof AttractionsDestinationSlugSlugRoute
  '/fr/destinations/$slug': typeof FrDestinationsSlugRoute
  '/fr/tour/$slug': typeof FrTourSlugRoute
  '/admin/attractions/': typeof AdminAttractionsIndexRoute
  '/admin/destinations/': typeof AdminDestinationsIndexRoute
  '/admin/tours/': typeof AdminToursIndexRoute
  '/admin/tours/$tourId/preview': typeof AdminToursTourIdPreviewRoute
  '/fr/attractions/$destinationSlug/$slug': typeof FrAttractionsDestinationSlugSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/attractions': typeof AttractionsRoute
  '/destinations': typeof DestinationsRoute
  '/fr': typeof FrRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tour': typeof TourRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/taxonomies': typeof AdminTaxonomiesRoute
  '/admin/login': typeof AdminLoginRoute
  '/destination/berat': typeof DestinationBeratRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/fr/$slug': typeof FrSlugRoute
  '/fr/attractions': typeof FrAttractionsRoute
  '/fr/destinations': typeof FrDestinationsRoute
  '/fr/tour': typeof FrTourRoute
  '/tour/$slug': typeof TourSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/attractions/$placeId': typeof AdminAttractionsPlaceIdRoute
  '/admin/attractions/new': typeof AdminAttractionsNewRoute
  '/admin/destinations/$placeId': typeof AdminDestinationsPlaceIdRoute
  '/admin/destinations/new': typeof AdminDestinationsNewRoute
  '/admin/tours/$tourId': typeof AdminToursTourIdRoute
  '/admin/tours/new': typeof AdminToursNewRoute
  '/attractions/$destinationSlug/$slug': typeof AttractionsDestinationSlugSlugRoute
  '/fr/destinations/$slug': typeof FrDestinationsSlugRoute
  '/fr/tour/$slug': typeof FrTourSlugRoute
  '/admin/attractions': typeof AdminAttractionsIndexRoute
  '/admin/destinations': typeof AdminDestinationsIndexRoute
  '/admin/tours': typeof AdminToursIndexRoute
  '/admin/tours/$tourId/preview': typeof AdminToursTourIdPreviewRoute
  '/fr/attractions/$destinationSlug/$slug': typeof FrAttractionsDestinationSlugSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/attractions': typeof AttractionsRoute
  '/destinations': typeof DestinationsRoute
  '/fr': typeof FrRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tour': typeof TourRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/taxonomies': typeof AdminTaxonomiesRoute
  '/admin_/login': typeof AdminLoginRoute
  '/destination/berat': typeof DestinationBeratRoute
  '/destinations_/$slug': typeof DestinationsSlugRoute
  '/fr_/$slug': typeof FrSlugRoute
  '/fr_/attractions': typeof FrAttractionsRoute
  '/fr_/destinations': typeof FrDestinationsRoute
  '/fr_/tour': typeof FrTourRoute
  '/tour_/$slug': typeof TourSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/attractions/$placeId': typeof AdminAttractionsPlaceIdRoute
  '/admin/attractions/new': typeof AdminAttractionsNewRoute
  '/admin/destinations/$placeId': typeof AdminDestinationsPlaceIdRoute
  '/admin/destinations/new': typeof AdminDestinationsNewRoute
  '/admin/tours/$tourId': typeof AdminToursTourIdRoute
  '/admin/tours/new': typeof AdminToursNewRoute
  '/attractions_/$destinationSlug/$slug': typeof AttractionsDestinationSlugSlugRoute
  '/fr_/destinations_/$slug': typeof FrDestinationsSlugRoute
  '/fr_/tour_/$slug': typeof FrTourSlugRoute
  '/admin/attractions/': typeof AdminAttractionsIndexRoute
  '/admin/destinations/': typeof AdminDestinationsIndexRoute
  '/admin/tours/': typeof AdminToursIndexRoute
  '/admin_/tours/$tourId/preview': typeof AdminToursTourIdPreviewRoute
  '/fr_/attractions_/$destinationSlug/$slug': typeof FrAttractionsDestinationSlugSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/attractions'
    | '/destinations'
    | '/fr'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tour'
    | '/admin/media'
    | '/admin/reviews'
    | '/admin/taxonomies'
    | '/admin/login'
    | '/destination/berat'
    | '/destinations/$slug'
    | '/fr/$slug'
    | '/fr/attractions'
    | '/fr/destinations'
    | '/fr/tour'
    | '/tour/$slug'
    | '/admin/'
    | '/admin/attractions/$placeId'
    | '/admin/attractions/new'
    | '/admin/destinations/$placeId'
    | '/admin/destinations/new'
    | '/admin/tours/$tourId'
    | '/admin/tours/new'
    | '/attractions/$destinationSlug/$slug'
    | '/fr/destinations/$slug'
    | '/fr/tour/$slug'
    | '/admin/attractions/'
    | '/admin/destinations/'
    | '/admin/tours/'
    | '/admin/tours/$tourId/preview'
    | '/fr/attractions/$destinationSlug/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/attractions'
    | '/destinations'
    | '/fr'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tour'
    | '/admin/media'
    | '/admin/reviews'
    | '/admin/taxonomies'
    | '/admin/login'
    | '/destination/berat'
    | '/destinations/$slug'
    | '/fr/$slug'
    | '/fr/attractions'
    | '/fr/destinations'
    | '/fr/tour'
    | '/tour/$slug'
    | '/admin'
    | '/admin/attractions/$placeId'
    | '/admin/attractions/new'
    | '/admin/destinations/$placeId'
    | '/admin/destinations/new'
    | '/admin/tours/$tourId'
    | '/admin/tours/new'
    | '/attractions/$destinationSlug/$slug'
    | '/fr/destinations/$slug'
    | '/fr/tour/$slug'
    | '/admin/attractions'
    | '/admin/destinations'
    | '/admin/tours'
    | '/admin/tours/$tourId/preview'
    | '/fr/attractions/$destinationSlug/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/attractions'
    | '/destinations'
    | '/fr'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tour'
    | '/admin/media'
    | '/admin/reviews'
    | '/admin/taxonomies'
    | '/admin_/login'
    | '/destination/berat'
    | '/destinations_/$slug'
    | '/fr_/$slug'
    | '/fr_/attractions'
    | '/fr_/destinations'
    | '/fr_/tour'
    | '/tour_/$slug'
    | '/admin/'
    | '/admin/attractions/$placeId'
    | '/admin/attractions/new'
    | '/admin/destinations/$placeId'
    | '/admin/destinations/new'
    | '/admin/tours/$tourId'
    | '/admin/tours/new'
    | '/attractions_/$destinationSlug/$slug'
    | '/fr_/destinations_/$slug'
    | '/fr_/tour_/$slug'
    | '/admin/attractions/'
    | '/admin/destinations/'
    | '/admin/tours/'
    | '/admin_/tours/$tourId/preview'
    | '/fr_/attractions_/$destinationSlug/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AttractionsRoute: typeof AttractionsRoute
  DestinationsRoute: typeof DestinationsRoute
  FrRoute: typeof FrRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TourRoute: typeof TourRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DestinationBeratRoute: typeof DestinationBeratRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  FrSlugRoute: typeof FrSlugRoute
  FrAttractionsRoute: typeof FrAttractionsRoute
  FrDestinationsRoute: typeof FrDestinationsRoute
  FrTourRoute: typeof FrTourRoute
  TourSlugRoute: typeof TourSlugRoute
  AttractionsDestinationSlugSlugRoute: typeof AttractionsDestinationSlugSlugRoute
  FrDestinationsSlugRoute: typeof FrDestinationsSlugRoute
  FrTourSlugRoute: typeof FrTourSlugRoute
  AdminToursTourIdPreviewRoute: typeof AdminToursTourIdPreviewRoute
  FrAttractionsDestinationSlugSlugRoute: typeof FrAttractionsDestinationSlugSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tour_/$slug': {
      id: '/tour_/$slug'
      path: '/tour/$slug'
      fullPath: '/tour/$slug'
      preLoaderRoute: typeof TourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr_/tour': {
      id: '/fr_/tour'
      path: '/fr/tour'
      fullPath: '/fr/tour'
      preLoaderRoute: typeof FrTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr_/destinations': {
      id: '/fr_/destinations'
      path: '/fr/destinations'
      fullPath: '/fr/destinations'
      preLoaderRoute: typeof FrDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr_/attractions': {
      id: '/fr_/attractions'
      path: '/fr/attractions'
      fullPath: '/fr/attractions'
      preLoaderRoute: typeof FrAttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr_/$slug': {
      id: '/fr_/$slug'
      path: '/fr/$slug'
      fullPath: '/fr/$slug'
      preLoaderRoute: typeof FrSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations_/$slug': {
      id: '/destinations_/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/berat': {
      id: '/destination/berat'
      path: '/destination/berat'
      fullPath: '/destination/berat'
      preLoaderRoute: typeof DestinationBeratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/taxonomies': {
      id: '/admin/taxonomies'
      path: '/taxonomies'
      fullPath: '/admin/taxonomies'
      preLoaderRoute: typeof AdminTaxonomiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours/': {
      id: '/admin/tours/'
      path: '/tours'
      fullPath: '/admin/tours/'
      preLoaderRoute: typeof AdminToursIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations/': {
      id: '/admin/destinations/'
      path: '/destinations'
      fullPath: '/admin/destinations/'
      preLoaderRoute: typeof AdminDestinationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attractions/': {
      id: '/admin/attractions/'
      path: '/attractions'
      fullPath: '/admin/attractions/'
      preLoaderRoute: typeof AdminAttractionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/fr_/tour_/$slug': {
      id: '/fr_/tour_/$slug'
      path: '/fr/tour/$slug'
      fullPath: '/fr/tour/$slug'
      preLoaderRoute: typeof FrTourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr_/destinations_/$slug': {
      id: '/fr_/destinations_/$slug'
      path: '/fr/destinations/$slug'
      fullPath: '/fr/destinations/$slug'
      preLoaderRoute: typeof FrDestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions_/$destinationSlug/$slug': {
      id: '/attractions_/$destinationSlug/$slug'
      path: '/attractions/$destinationSlug/$slug'
      fullPath: '/attractions/$destinationSlug/$slug'
      preLoaderRoute: typeof AttractionsDestinationSlugSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tours/new': {
      id: '/admin/tours/new'
      path: '/tours/new'
      fullPath: '/admin/tours/new'
      preLoaderRoute: typeof AdminToursNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours/$tourId': {
      id: '/admin/tours/$tourId'
      path: '/tours/$tourId'
      fullPath: '/admin/tours/$tourId'
      preLoaderRoute: typeof AdminToursTourIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations/new': {
      id: '/admin/destinations/new'
      path: '/destinations/new'
      fullPath: '/admin/destinations/new'
      preLoaderRoute: typeof AdminDestinationsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations/$placeId': {
      id: '/admin/destinations/$placeId'
      path: '/destinations/$placeId'
      fullPath: '/admin/destinations/$placeId'
      preLoaderRoute: typeof AdminDestinationsPlaceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attractions/new': {
      id: '/admin/attractions/new'
      path: '/attractions/new'
      fullPath: '/admin/attractions/new'
      preLoaderRoute: typeof AdminAttractionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attractions/$placeId': {
      id: '/admin/attractions/$placeId'
      path: '/attractions/$placeId'
      fullPath: '/admin/attractions/$placeId'
      preLoaderRoute: typeof AdminAttractionsPlaceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/fr_/attractions_/$destinationSlug/$slug': {
      id: '/fr_/attractions_/$destinationSlug/$slug'
      path: '/fr/attractions/$destinationSlug/$slug'
      fullPath: '/fr/attractions/$destinationSlug/$slug'
      preLoaderRoute: typeof FrAttractionsDestinationSlugSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/tours/$tourId/preview': {
      id: '/admin_/tours/$tourId/preview'
      path: '/admin/tours/$tourId/preview'
      fullPath: '/admin/tours/$tourId/preview'
      preLoaderRoute: typeof AdminToursTourIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminMediaRoute: typeof AdminMediaRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminTaxonomiesRoute: typeof AdminTaxonomiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAttractionsPlaceIdRoute: typeof AdminAttractionsPlaceIdRoute
  AdminAttractionsNewRoute: typeof AdminAttractionsNewRoute
  AdminDestinationsPlaceIdRoute: typeof AdminDestinationsPlaceIdRoute
  AdminDestinationsNewRoute: typeof AdminDestinationsNewRoute
  AdminToursTourIdRoute: typeof AdminToursTourIdRoute
  AdminToursNewRoute: typeof AdminToursNewRoute
  AdminAttractionsIndexRoute: typeof AdminAttractionsIndexRoute
  AdminDestinationsIndexRoute: typeof AdminDestinationsIndexRoute
  AdminToursIndexRoute: typeof AdminToursIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMediaRoute: AdminMediaRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminTaxonomiesRoute: AdminTaxonomiesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAttractionsPlaceIdRoute: AdminAttractionsPlaceIdRoute,
  AdminAttractionsNewRoute: AdminAttractionsNewRoute,
  AdminDestinationsPlaceIdRoute: AdminDestinationsPlaceIdRoute,
  AdminDestinationsNewRoute: AdminDestinationsNewRoute,
  AdminToursTourIdRoute: AdminToursTourIdRoute,
  AdminToursNewRoute: AdminToursNewRoute,
  AdminAttractionsIndexRoute: AdminAttractionsIndexRoute,
  AdminDestinationsIndexRoute: AdminDestinationsIndexRoute,
  AdminToursIndexRoute: AdminToursIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AttractionsRoute: AttractionsRoute,
  DestinationsRoute: DestinationsRoute,
  FrRoute: FrRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TourRoute: TourRoute,
  AdminLoginRoute: AdminLoginRoute,
  DestinationBeratRoute: DestinationBeratRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  FrSlugRoute: FrSlugRoute,
  FrAttractionsRoute: FrAttractionsRoute,
  FrDestinationsRoute: FrDestinationsRoute,
  FrTourRoute: FrTourRoute,
  TourSlugRoute: TourSlugRoute,
  AttractionsDestinationSlugSlugRoute: AttractionsDestinationSlugSlugRoute,
  FrDestinationsSlugRoute: FrDestinationsSlugRoute,
  FrTourSlugRoute: FrTourSlugRoute,
  AdminToursTourIdPreviewRoute: AdminToursTourIdPreviewRoute,
  FrAttractionsDestinationSlugSlugRoute: FrAttractionsDestinationSlugSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
